name = "supportoteam"
main = "worker.js"              # ‚Üê qui il nome deve essere ESATTAMENTE il tuo file
compatibility_date = "2025-01-01"

[vars]
ALLOWED_ORIGINS = "*"
GH_BRANCH = "main"
GH_OWNER = "checcoroma91"
GH_REPO  = "SupportoTeam"
